# Some convenience requests using VSCode's REST Client extension.
# Extension automatically saves cookies to ~/.rest-client/cookie.json.

# Static values
@baseUrl = http://127.0.0.1:5000

# Dynamic values (change after receiving new IDs
@userId = ec13d248-8b75-4970-b65d-3302f901a631
@userProfileId = da7aa344-9726-4e60-8b62-23594c37d75d

# @name registerUser
POST {{baseUrl}}/api/register
content-type: application/json

{
    "username": "test",
    "password": "test",
    "email": "text@example.com"
}


###

# @name loginUser
POST {{baseUrl}}/api/login
content-type: application/json

{
    "username": "test",
    "password": "test"
}

### 

# @name createUserProfile
POST {{baseUrl}}/api/user-profile
content-type: application/json

{
    "userId": "ec13d248-8b75-4970-b65d-3302f901a631",
    "email": "test@example.com",
    "phoneNo": "test",
    "nric": "test",
    "firstName": "test",
    "lastName": "test",
    "dob": "1970-01-01",
    "gender": "M",
    "occupation": "test",
    "address": "test",
    "postalCode": "test"
}

### 

# @name findUserProfiles
GET {{baseUrl}}/api/user-profile

### 

# @name getUserProfile
GET {{baseUrl}}/api/user-profile/{{userProfileId}}

### 

# @name updateUserProfile
PUT {{baseUrl}}/api/user-profile/{{userProfileId}}
content-type: application/json

{
    "email": "test@example.com",
    "phoneNo": "test",
    "nric": "test",
    "firstName": "test",
    "lastName": "test",
    "dob": "1970-01-01",
    "gender": "F",
    "occupation": "test",
    "address": "test",
    "postalCode": "test"
}

### 

# @name deleteUserProfile
DELETE {{baseUrl}}/api/user-profile/{{userProfileId}}

###