openapi: 3.0.1
info:
  title: Pawscore
  description: This is an API documentation for Pawscore. You may review the API schema
    and/or trigger web API calls here.
  termsOfService: ""
  contact:
    email: samuelpua@better.sg
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /api
tags:
- name: auth
  description: Authentication & Authorization
- name: booking
  description: Appointment booking
- name: upload
  description: Upload & download of file attachments
- name: animal
  description: View and manage shelter animals
paths:
  /register:
    post:
      tags:
      - auth
      summary: Register
      operationId: register
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
                email:
                  type: string
                  description: Password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /login:
    post:
      tags:
      - auth
      summary: Login
      operationId: login
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /booking:
    post:
      tags:
      - booking
      summary: Create a new booking
      operationId: createBooking
      requestBody:
        description: Create a new booking
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /upload:
    post:
      tags:
      - upload
      summary: Upload a new file attachment
      operationId: uploadFile
      requestBody:
        description: Create a new file attachment
        content:
          application/json:
            schema:
              properties:
                originalFilename:
                  type: string
                  description: Filename
                base64File:
                  type: string
                  description: File in base64
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /upload/{fileId}:
    get:
      tags:
      - upload
      summary: Upload a new file attachment
      operationId: getFile
      parameters:
        - name: fileId
          in: path
          description: File upload ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /animal:
    get:
      tags:
      - animal
      summary: Retrieve all animals
      operationId: getAnimals
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
  /animal/{id}:
    get:
      tags:
      - animal
      summary: Retrieve animal by id
      operationId: getAnimalById
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        payload:
          type: object
    Booking:
      type: object
      properties:
        shelterId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Animal:
      type: object
      properties:
        id:
          type: string
          format: uuid
        shelterId:
          type: string
          format: uuid
        adoptionStatus:
          type: string
          enum: [Ongoing, Adopted, Archived]
        species:
          type: string
          enum: [Cat, Dog, Others]
        name:
          type: string
        description:
          type: string
        healthIssues:
          type: string
        gender:
          type: string
          enum: [F, M]
        ageMonths:
          type: integer
          nullable: true
        sizeCm:
          type: integer
          nullable: true
        breed:
          type: string
          nullable: true
        color:
          type: string
        weightKg:
          type: integer
          nullable: true
        furLength:
          type: string
          nullable: true
        vaccinated:
          type: boolean
          nullable: true
        dewormed:
          type: boolean
          nullable: true
        sterilized:
          type: boolean
          nullable: true
        adoptionFee:
          type: number
          nullable: true
        intakeDate:
          type: string
          format: date
        animalImages:
          type: array
          items:
            $ref: '#/components/schemas/AnimalImage'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    AnimalImage:
      type: object
      properties:
        animalId:
          type: string
          format: uuid
        photoUrl:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: connect.sid
      in: cookie
