openapi: 3.0.1
info:
  title: Pawscore
  description: This is an API documentation for Pawscore. You may review the API schema
    and/or trigger web API calls here.
  termsOfService: ""
  contact:
    email: samuelpua@better.sg
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /api
tags:
- name: auth
  description: Authentication & Authorization
- name: booking
  description: Appointment booking
- name: upload
  description: Upload & download of file attachments
- name: animal
  description: View and manage shelter animals
- name: user profile
  description: View and manage user profile
- name: shelter
  description: View and manage shelters
paths:
  /register:
    post:
      tags:
      - auth
      summary: Register
      operationId: register
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
                email:
                  type: string
                  description: Password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /login:
    post:
      tags:
      - auth
      summary: Login
      operationId: login
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /booking:
    post:
      tags:
      - booking
      summary: Create a new booking
      operationId: createBooking
      requestBody:
        description: Create a new booking
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /upload:
    post:
      tags:
      - upload
      summary: Upload a new file attachment
      operationId: uploadFile
      requestBody:
        description: Create a new file attachment
        content:
          application/json:
            schema:
              properties:
                originalFilename:
                  type: string
                  description: Filename
                base64File:
                  type: string
                  description: File in base64
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /upload/{fileId}:
    get:
      tags:
      - upload
      summary: Upload a new file attachment
      operationId: getFile
      parameters:
        - name: fileId
          in: path
          description: File upload ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - cookieAuth: []
      x-codegen-request-body-name: body
  /animal:
    get:
      tags:
      - animal
      summary: Retrieve all animals
      operationId: getAnimals
      responses:
        200:
          description: Returns list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
  /animal/{id}:
    get:
      tags:
      - animal
      summary: Retrieve animal by id
      operationId: getAnimalById
      responses:
        200:
          description: Returns animal with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
        404:
          description: Animal with the specified id was not found
  /user-profile:
    get:
      tags:
        - user profile
      summary: Retrieve all user profiles
      operationId: getUserProfiles
      responses:
        200:
          description: Returns list of user profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
    post:
      tags:
      - user profile
      summary: Create a new user profile
      operationId: createUserProfile
      requestBody:
        description: Create a new user profile
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  /user-profile/{userProfileId}:
    get:
      tags:
        - user profile
      summary: Retrieve user profile
      operationId: getUserProfile
      responses:
        200:
          description: Returns a specific user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      tags:
        - user profile
      summary: Update user profile
      operationId: putUserProfile
      requestBody:
        description: Updates a user profile
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseUserProfile'
        required: true
      responses:
        200:
          description: Returns updated user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    delete:
      tags:
        - user profile
      summary: Delete user profile
      operationId: deleteUserProfile
      responses:
        200:
          description: Deletes a specific user profile
  /shelter:
    get:
      tags:
      - shelter
      summary: Retrieve all shelters
      responses:
        200:
          description: Returns list of shelters
    post:
      tags:
      - shelter
      summary: Create a new shelter
      responses:
        201:
          description: Created
  /shelter/{shelterId}:
    get:
      tags:
      - shelter
      summary: Retrieve shelter
      responses:
        200:
          description: Returns a specific shelter

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        payload:
          type: object
    Booking:
      type: object
      properties:
        shelterId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Animal:
      type: object
      properties:
        id:
          type: string
          format: uuid
        shelterId:
          type: string
          format: uuid
        adoptionStatus:
          type: string
          enum: [Ongoing, Adopted, Archived]
        species:
          type: string
          enum: [Cat, Dog, Others]
        name:
          type: string
        description:
          type: string
        healthIssues:
          type: string
        gender:
          type: string
          enum: [F, M]
        ageMonths:
          type: integer
          nullable: true
        sizeCm:
          type: integer
          nullable: true
        breed:
          type: string
          nullable: true
        color:
          type: string
        weightKg:
          type: integer
          nullable: true
        furLength:
          type: string
          nullable: true
        vaccinated:
          type: boolean
          nullable: true
        dewormed:
          type: boolean
          nullable: true
        sterilised:
          type: boolean
          nullable: true
        toiletTrained:
          type: boolean
          nullable: true
        adoptionFee:
          type: number
          nullable: true
        intakeDate:
          type: string
          format: date
        visible:
          type: boolean
        animalImages:
          type: array
          items:
            $ref: '#/components/schemas/AnimalImage'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    AnimalImage:
      type: object
      properties:
        animalId:
          type: string
          format: uuid
        photoUrl:
          type: string
          format: uri
        thumbnailUrl:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Shelter:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        country:
          type: string
        contact:
          type: string
        registrationNo:
          type: string
          nullable: true
    BaseUserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        authUserId:
          type: string
          format: uuid
        email:
          type: string
        phoneNo:
          type: string
        nric:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dob:
          type: string
          format: date
          description: Format as "YYYY-MM-DD"
        gender:
          type: string
          enum: [F, M]
        occupation:
          type: string
        address:
          type: string
        postalCode:
          type: string
    UserProfile:
      allOf:
        - $ref: '#/components/schemas/BaseUserProfile'
      required:
        - id
        - authUserId
        - email
        - phoneNo
        - nric
        - firstName
        - lastName
        - dob
        - gender
        - occupation
        - address
        - postalCode
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: connect.sid
      in: cookie
