name: Deploy Release to Production
on:
  release:
    types: [published]

jobs:
  Deploy-Production:
    name: Deploy a release using git hash of release
    environment: production
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      HASH: $(git rev-parse --short "$GITHUB_SHA")

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GC_GITHUB_ACTIONS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Tag existing image as release with git hash in Google Artifact Registry
        run: |
          echo "$GITHUB_SHA"
          echo $GITHUB_SHA
          echo $(git rev-parse --short "$GITHUB_SHA")
          echo $HASH
          gcloud artifacts docker tags add asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:$(git rev-parse --short "$GITHUB_SHA") release
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:release
          service: ${{ secrets.SERVICE_NAME }}
          region: asia-southeast1
