name: Build
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build image
    environment: development
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      # SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GC_GITHUB_ACTIONS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Build docker image
      # - name: Image
      #   run: |-
      #     docker build -f docker/Dockerfile -t asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:latest .
      # docker build --build-arg -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      # Push image to Google Artifact Registry
      - name: Build
        run: |-
          docker push asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:latest
