name: Build and Deploy to Development
on:
  push:
    branches:
      - 'master'

jobs:
  Build-Deploy-Development:
    name: Build image, send to Artifact Registry, deploy to Cloud Run
    environment: development
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GC_GITHUB_ACTIONS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Build docker image
        run: |
          GIT_SHORT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker build -f docker/Dockerfile -t build:latest .
          docker tag build:latest asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:latest
          docker tag build:latest asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:$GIT_SHORT_HASH
      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Push image to Google Artifact Registry
        run: |
          GIT_SHORT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          docker push asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:latest
          docker push asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:$GIT_SHORT_HASH
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: asia-southeast1-docker.pkg.dev/pawscore/pawscore/pawscore-image:latest
          service: ${{ secrets.SERVICE_NAME }}
          region: asia-southeast1
